spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: comep1522w
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update